apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration
        image: registration:v1
        ports:
        - containerPort: 5000

